modLoader = "javafml"
loaderVersion = "[43,)"
license="All rights reserved"

[[mods]]
modId="squatgrow"
version="${version}"
displayName="Squat Grow"
logoFile="examplemod.png"
credits="Me"
authors="Gaz"
description='''
Squat up and down to grow your plant
'''

[[dependencies.squatgrow]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squatgrow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squatgrow]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"