modLoader = "javafml"
loaderVersion = "[1,)"
license="All rights reserved"

[[mods]]
modId="squatgrow"
version="${version}"
displayName="Squat Grow"
logoFile="examplemod.png"
credits="Me"
authors="Gaz"
description='''
Squat up and down to grow your plant
'''

[[mixins]]
config = "squatgrow.mixins.json"

[[dependencies.squatgrow]]
modId = "neoforge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squatgrow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squatgrow]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.8,)"
ordering = "AFTER"
side = "BOTH"