modLoader = "javafml"
loaderVersion = "[2,)"
license="All rights reserved"

[[mods]]
modId="squatgrow"
version="${version}"
displayName="Squat Grow"
logoFile="examplemod.png"
credits="Me"
authors="Gaz"
description='''
Squat up and down to grow your plant
'''

[[mixins]]
config = "squatgrow.mixins.json"

[[dependencies.squatgrow]]
modId = "neoforge"
required = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squatgrow]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squatgrow]]
modId = "architectury"
required = true
versionRange = "[13.0.1,)"
ordering = "AFTER"
side = "BOTH"